### ISSUE TITLE
request: add an option for 24-hour clock(s)

### ISSUE THREAD

**Issue by tocic** [jonathanlermitage/ij-worldclock#4]
Could you please add an option for displaying time in [24-hour format](https://en.wikipedia.org/wiki/24-hour_clock)?

**Comment by tocic** [comment]
Thanks. I've tested the manually built 1.4 version and it works as expected. Can you bump [the version in the marketplace](https://plugins.jetbrains.com/plugin/17816-world-clock)?

**Comment by jonathanlermitage** [comment]
Hi!  
v1.4 has been submitted this weekend. JetBrains will validate and publish the new release very soon, usually within 2 business days.
