### ISSUE TITLE
India Standard Time

### ISSUE THREAD

**Issue by erickczh** [jonathanlermitage/ij-worldclock#5]
I could not find India Standard time, where I typically use Asia/Delhi. Look at the source code, you have the India flag included (https://github.com/jonathanlermitage/ij-worldclock/blob/master/src/main/resources/worldclock/default_flags/in.svg), so I am confident it might just be me not being familiar with the search rules. Can you please point me to the correct city for this timezone selection? Thanks!

**Comment by jonathanlermitage** [comment]
@erickczh Unfortunately, the JVM doesn't seem to support Delhi timezone. I don't know why.  
List of supported timezone is here: https://github.com/jonathanlermitage/ij-worldclock/blob/master/src/main/java/lermitage/intellij/worldclock/DateUtils.java#L41. Only two Indian timezones are supported (you can search for "in" in the file, this is the flag's code): Kolkata and Calcutta. If my understanding is correct, Kolkata is the new name of Calcutta?  
-> Delhi seems to have similar timezone rules: UTC+5:30 (I'm referring to [Delhi](https://www.timeanddate.com/time/zone/india/delhi-state) and [Kolkata](https://www.timeanddate.com/time/zone/india/kolkata) info provided by www.timeanddate.com), and no daylight saving rules. You can probably use this timezone.  
Also, if you think this is correct, I can add Delhi as an alias of Kolkata. This way, users will be able to pick Delhi, and the result will remain valid. What do you think?

**Comment by erickczh** [comment]
If it is flexible for you to add new cities (assuming you are not importing city names from an external source), it will be good to include the following top cities besides Kolkata:
Asia/Mumbai
Asia/Bangalore
Asia/Hyderabad
Asia/Delhi
I just searched on the wiki and found out that India is now unioned under one single timezone (UTC +5:30, with no daylight saving).

**Comment by jonathanlermitage** [comment]
Fixed. Will be part of the next release :)
